require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CodepensController do

  def mock_codepen(stubs={})
    @mock_codepen ||= mock_model(Codepen, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all codepens as @codepens" do
      Codepen.stub(:all) { [mock_codepen] }
      get :index
      assigns(:codepens).should eq([mock_codepen])
    end
  end

  describe "GET show" do
    it "assigns the requested codepen as @codepen" do
      Codepen.stub(:find).with("37") { mock_codepen }
      get :show, :id => "37"
      assigns(:codepen).should be(mock_codepen)
    end
  end

  describe "GET new" do
    it "assigns a new codepen as @codepen" do
      Codepen.stub(:new) { mock_codepen }
      get :new
      assigns(:codepen).should be(mock_codepen)
    end
  end

  describe "GET edit" do
    it "assigns the requested codepen as @codepen" do
      Codepen.stub(:find).with("37") { mock_codepen }
      get :edit, :id => "37"
      assigns(:codepen).should be(mock_codepen)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created codepen as @codepen" do
        Codepen.stub(:new).with({'these' => 'params'}) { mock_codepen(:save => true) }
        post :create, :codepen => {'these' => 'params'}
        assigns(:codepen).should be(mock_codepen)
      end

      it "redirects to the created codepen" do
        Codepen.stub(:new) { mock_codepen(:save => true) }
        post :create, :codepen => {}
        response.should redirect_to(codepen_url(mock_codepen))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved codepen as @codepen" do
        Codepen.stub(:new).with({'these' => 'params'}) { mock_codepen(:save => false) }
        post :create, :codepen => {'these' => 'params'}
        assigns(:codepen).should be(mock_codepen)
      end

      it "re-renders the 'new' template" do
        Codepen.stub(:new) { mock_codepen(:save => false) }
        post :create, :codepen => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested codepen" do
        Codepen.stub(:find).with("37") { mock_codepen }
        mock_codepen.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :codepen => {'these' => 'params'}
      end

      it "assigns the requested codepen as @codepen" do
        Codepen.stub(:find) { mock_codepen(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:codepen).should be(mock_codepen)
      end

      it "redirects to the codepen" do
        Codepen.stub(:find) { mock_codepen(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(codepen_url(mock_codepen))
      end
    end

    describe "with invalid params" do
      it "assigns the codepen as @codepen" do
        Codepen.stub(:find) { mock_codepen(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:codepen).should be(mock_codepen)
      end

      it "re-renders the 'edit' template" do
        Codepen.stub(:find) { mock_codepen(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested codepen" do
      Codepen.stub(:find).with("37") { mock_codepen }
      mock_codepen.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the codepens list" do
      Codepen.stub(:find) { mock_codepen }
      delete :destroy, :id => "1"
      response.should redirect_to(codepens_url)
    end
  end

end
