require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LessonsController do

  def mock_lesson(stubs={})
    @mock_lesson ||= mock_model(Lesson, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lessons as @lessons" do
      Lesson.stub(:all) { [mock_lesson] }
      get :index
      assigns(:lessons).should eq([mock_lesson])
    end
  end

  describe "GET show" do
    it "assigns the requested lesson as @lesson" do
      Lesson.stub(:find).with("37") { mock_lesson }
      get :show, :id => "37"
      assigns(:lesson).should be(mock_lesson)
    end
  end

  describe "GET new" do
    it "assigns a new lesson as @lesson" do
      Lesson.stub(:new) { mock_lesson }
      get :new
      assigns(:lesson).should be(mock_lesson)
    end
  end

  describe "GET edit" do
    it "assigns the requested lesson as @lesson" do
      Lesson.stub(:find).with("37") { mock_lesson }
      get :edit, :id => "37"
      assigns(:lesson).should be(mock_lesson)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lesson as @lesson" do
        Lesson.stub(:new).with({'these' => 'params'}) { mock_lesson(:save => true) }
        post :create, :lesson => {'these' => 'params'}
        assigns(:lesson).should be(mock_lesson)
      end

      it "redirects to the created lesson" do
        Lesson.stub(:new) { mock_lesson(:save => true) }
        post :create, :lesson => {}
        response.should redirect_to(lesson_url(mock_lesson))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lesson as @lesson" do
        Lesson.stub(:new).with({'these' => 'params'}) { mock_lesson(:save => false) }
        post :create, :lesson => {'these' => 'params'}
        assigns(:lesson).should be(mock_lesson)
      end

      it "re-renders the 'new' template" do
        Lesson.stub(:new) { mock_lesson(:save => false) }
        post :create, :lesson => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lesson" do
        Lesson.stub(:find).with("37") { mock_lesson }
        mock_lesson.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lesson => {'these' => 'params'}
      end

      it "assigns the requested lesson as @lesson" do
        Lesson.stub(:find) { mock_lesson(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lesson).should be(mock_lesson)
      end

      it "redirects to the lesson" do
        Lesson.stub(:find) { mock_lesson(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lesson_url(mock_lesson))
      end
    end

    describe "with invalid params" do
      it "assigns the lesson as @lesson" do
        Lesson.stub(:find) { mock_lesson(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lesson).should be(mock_lesson)
      end

      it "re-renders the 'edit' template" do
        Lesson.stub(:find) { mock_lesson(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lesson" do
      Lesson.stub(:find).with("37") { mock_lesson }
      mock_lesson.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lessons list" do
      Lesson.stub(:find) { mock_lesson }
      delete :destroy, :id => "1"
      response.should redirect_to(lessons_url)
    end
  end

end
